// Generated by CoffeeScript 1.3.3
(function() {
  var csv, request, toTestObject, util, _;

  request = require('request');

  csv = require('csv');

  _ = require('underscore');

  util = require('util');

  request('http://accessibility.egovmon.no/en/pagecheck2.0/?url=http%3A%2F%2Falexanderte.com%2F&export=occurences', function(error, response, body) {
    var ds, rows;
    if (error !== null) {
      throw new Exception('Could not fetch CSV-file from eGovMon Checker.');
    }
    rows = [];
    ds = {};
    return csv().from(body).transform(function(data) {
      return rows.push(data);
    }).on('end', function() {
      var row, _i, _len;
      rows = _.map(_.rest(rows), toTestObject);
      for (_i = 0, _len = rows.length; _i < _len; _i++) {
        row = rows[_i];
        if (!(ds[row.successCriterion] != null)) {
          ds[row.successCriterion] = {};
        }
        if (!(ds[row.successCriterion][row.test] != null)) {
          ds[row.successCriterion][row.test] = [];
        }
        ds[row.successCriterion][row.test].push({
          line: row.line,
          column: row.column,
          result: row.result,
          resultDescription: row.resultDescription,
          resultDetails: row.resultDetails
        });
      }
      return console.log(util.inspect(ds, false, null));
    });
  });

  toTestObject = function(row) {
    return {
      line: row[2],
      column: row[3],
      successCriterion: row[4],
      test: row[5],
      result: row[6],
      resultDescription: row[7],
      resultDetails: row[8]
    };
  };

}).call(this);
