// Generated by CoffeeScript 1.3.3
(function() {
  var csv, request, toNumber, toTestObject, _;

  request = require('request');

  csv = require('csv');

  _ = require('underscore');

  request('http://accessibility.egovmon.no/en/pagecheck2.0/?url=http%3A%2F%2Falexanderte.com%2F&export=tests', function(error, response, body) {
    var rows;
    if (error !== null) {
      throw new Exception('error');
    }
    rows = [];
    return csv().from(body).transform(function(data) {
      return rows.push(data);
    }).on('end', function() {
      return console.log(_.filter(_.map(_.rest(rows), toTestObject), function(o) {
        return o.verifyOccurences > 0;
      }));
    });
  });

  toTestObject = function(row) {
    return {
      successCriterion: row[2],
      testName: row[3],
      failOccurences: toNumber(row[4]),
      verifyOccurences: toNumber(row[5]),
      passOccurences: toNumber(row[6])
    };
  };

  toNumber = function(n) {
    if (n === '') {
      return 0;
    } else {
      return parseInt(n);
    }
  };

}).call(this);
