// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone'], function(Backbone) {
    return Backbone.Router.extend({
      routes: {
        '': 'home',
        'test': 'test',
        'test/:id': 'test',
        'result': 'result'
      }
    });
  });

}).call(this);
