// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      el: '#home-view',
      events: {
        'click button#set-web-page-2': 'setWebPage'
      },
      initialize: function() {
        this.render();
        this.options.router.bind('all', function(route) {
          if (route === 'route:home') {
            return this.$el.show();
          } else {
            return this.$el.hide();
          }
        }, this);
        this.options.locale.on('change:locale', this.render, this);
        this.options.testRun.bind('change:state', this.render, this);
        return this.options.testRun.bind('change:webPage', function() {
          return $('#web-page-2').val(this.options.testRun.get('webPage'));
        }, this);
      },
      render: function() {
        this.$el.html(_.template($('#home-template').html(), {
          webPage: this.options.testRun.get('webPage'),
          userTestingTool: this.options.locale.translate('home_user_testing_tool'),
          description: this.options.locale.translate('home_description'),
          enterWebPage: this.options.locale.translate('home_enter_web_page'),
          startTesting: this.options.locale.translate('home_start_testing'),
          reportIssue: this.options.locale.translate('home_report_issue'),
          state: this.options.testRun.get('state')
        }));
        return $('#web-page-2').focus();
      },
      setWebPage: function() {
        this.options.testRun.setWebPage($('#web-page-2').val());
        return this.options.router.navigate('test', {
          trigger: true
        });
      }
    });
  });

}).call(this);
