// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone', 'underscore', 'jquery', 'jed'], function(Backbone, _, $) {
    return Backbone.View.extend({
      el: '#home-view',
      initialize: function() {
        this.render();
        this.options.router.bind('all', function(route) {
          if (route === 'route:home') {
            return this.$el.show();
          } else {
            return this.$el.hide();
          }
        }, this);
        this.model.bind('change:webPage', function() {
          return $('#web-page-2').val(this.model.get('webPage'));
        }, this);
        this.model.on('languageUpdated', function() {
          console.log('languageUpdated');
          return this.render();
        }, this);
        this.model.on('appLoaded', function() {
          console.log(3);
          return this.render();
        }, this);
        return this.model.bind('change:state', function() {
          if (this.model.get('state') === 'loaded' || this.model.get('state') === 'error') {
            $('#web-page-2').removeClass('disabled');
            $('#web-page-2').attr('disabled', false);
            $('#set-web-page-2').removeClass('disabled');
            return $('#set-web-page-2').attr('disabled', false);
          } else {
            $('#web-page-2').addClass('disabled');
            $('#web-page-2').attr('disabled', true);
            $('#web-page-2').blur();
            $('#set-web-page-2').addClass('disabled');
            return $('#set-web-page-2').attr('disabled', true);
          }
        }, this);
      },
      render: function() {
        if (this.model.get('jed') === void 0) {
          return;
        }
        console.log(4);
        this.$el.html(_.template($('#home-template').html(), {
          webPage: this.model.get('webPage'),
          userTestingTool: this.model.translate('home_user_testing_tool'),
          description: this.model.translate('home_description'),
          enterWebPage: this.model.translate('home_enter_web_page'),
          startTesting: this.model.translate('home_start_testing'),
          reportIssue: this.model.translate('home_report_issue')
        }));
        return $('#web-page-2').focus();
      },
      events: {
        'click button#set-web-page-2': 'setWebPage'
      },
      setWebPage: function() {
        if (this.model.get('webPage') === $('#web-page-2').val()) {
          return this.options.router.navigate('test', true);
        } else {
          return this.model.setWebPage($('#web-page-2').val());
        }
      }
    });
  });

}).call(this);
