// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      el: '#iframe-view',
      initialize: function() {
        this.render();
        this.options.router.bind('all', function(route) {
          if (route === 'route:test') {
            if (this.options.testRun.get('state') !== 'error') {
              return this.$el.show();
            }
          } else {
            return this.$el.hide();
          }
        }, this);
        return this.options.testRun.bind('change:webPage', this.render, this);
      },
      render: function() {
        return this.$el.html(_.template($('#iframe-template').html(), {
          'webPage': this.options.testRun.get('webPage')
        }));
      }
    });
  });

}).call(this);
