// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      el: '#navbar-view',
      events: {
        'click button#set-web-page': 'setWebPage',
        'click a.language': 'changeLanguage'
      },
      initialize: function() {
        this.render();
        this.options.router.bind('all', this.render, this);
        this.options.locale.on('change:locale', this.render, this);
        return this.options.testRun.bind('change:state', this.render, this);
      },
      render: function() {
        return this.$el.html(_.template($('#navbar-template').html(), {
          webPage: this.options.testRun.get('webPage'),
          language: this.options.locale.get('locale'),
          state: this.options.testRun.get('state'),
          route: this.getCurrentRoute(),
          _test: this.options.locale.translate('navbar_test'),
          _results: this.options.locale.translate('navbar_results'),
          _language: this.options.locale.translate('navbar_language'),
          _languageEnglish: this.options.locale.translate('navbar_language_english'),
          _languageNorwegian: this.options.locale.translate('navbar_language_norwegian'),
          _set: this.options.locale.translate('navbar_set')
        }));
      },
      getCurrentRoute: function() {
        if (!Backbone.history.fragment) {
          return 'home';
        } else if (Backbone.history.fragment.substr(0, 4) === 'test') {
          return 'test';
        } else {
          return Backbone.history.fragment;
        }
      },
      setWebPage: function() {
        this.options.testRun.setWebPage($('#web-page').val());
        return this.options.router.navigate('test', {
          trigger: true
        });
      },
      changeLanguage: function(e) {
        return this.options.locale.setLocale(e.currentTarget.dataset['language']);
      }
    });
  });

}).call(this);
