// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      el: '#test-view',
      events: {
        'click button.answer': 'clickAnswer'
      },
      initialize: function() {
        this.render();
        this.options.router.bind('all', function(route, currentTest) {
          if (route === 'route:test') {
            this.options.testRun.set('currentTest', currentTest === void 0 ? 0 : parseInt(currentTest));
            if (this.options.testRun.get('currentTest') === 0) {
              return this.$el.slideDown();
            } else {
              return this.$el.show();
            }
          } else {
            return this.$el.hide();
          }
        }, this);
        this.options.locale.on('change:locale', this.render, this);
        this.options.testRun.bind('change:state', this.render, this);
        return this.options.testRun.bind('change:currentTest', this.render, this);
      },
      render: function() {
        var answers, test, that;

        switch (this.options.testRun.get('state')) {
          case 'error':
            return this.$el.html(_.template($('#test-error').html(), {
              'webPage': this.options.testRun.get('webPage')
            }));
          case 'loading':
            return this.$el.html(_.template($('#test-loading').html(), {
              'webPage': this.options.testRun.get('webPage')
            }));
          default:
            if (!this.options.testRun.getCurrentTest()) {
              this.$el.html(_.template($('#test-nothing-to-test').html(), {
                'webPage': this.options.testRun.get('webPage')
              }));
              return;
            }
            test = this.options.testRun.getCurrentTest();
            that = this;
            answers = _.map(test.get('answers'), function(a) {
              return {
                value: a,
                _value: that.options.locale.translate('test_answer_' + a)
              };
            });
            this.$el.html(_.template($('#test-progress').html(), {
              'progress': this.options.testRun.progress()
            }) + _.template($(test.get('template')).html(), {
              '_question': this.options.locale.translate('test_question_' + test.get('testId') + '-' + test.get('testResultId'), test.get('questionValues')),
              '_previousTest': this.options.locale.translate('test_previous_test'),
              '_skipTest': this.options.locale.translate('test_skip_test'),
              'answers': answers,
              'nextUrl': this.nextUrl(),
              'previousUrl': this.previousUrl(),
              'previousExtraClass': this.previousExtraClass()
            }));
            return $('html, body').animate({
              scrollTop: 0
            }, 'fast');
        }
      },
      previousExtraClass: function() {
        if (this.options.testRun.isAtFirst() === true) {
          return 'disabled';
        }
      },
      previousUrl: function() {
        if (this.options.testRun.isAtFirst() === true) {
          return '#test/' + (this.options.testRun.get('currentTest'));
        } else {
          return '#test/' + (this.options.testRun.get('currentTest') - 1);
        }
      },
      nextUrl: function() {
        if (this.options.testRun.isAtLast() === true) {
          return '#result';
        } else {
          return '#test/' + (this.options.testRun.get('currentTest') + 1);
        }
      },
      clickAnswer: function(el) {
        this.options.testRun.setAnswer(el.currentTarget.value);
        if (this.options.testRun.isAtLast() === true) {
          return '#result';
        } else {
          return this.options.testRun.nextTest();
        }
      }
    });
  });

}).call(this);
