// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone', 'views/navbar', 'views/iframe', 'views/home', 'views/test', 'views/result'], function(Backbone, NavbarView, IframeView, HomeView, TestView, ResultView) {
    return Backbone.View.extend({
      initialize: function() {
        var homeView, iframeView, navbarView, resultView, testView;

        navbarView = new NavbarView(this.options);
        iframeView = new IframeView(this.options);
        homeView = new HomeView(this.options);
        testView = new TestView(this.options);
        return resultView = new ResultView(this.options);
      }
    });
  });

}).call(this);
