// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      el: '#home-view',
      render: function() {
        return this.$el.html(_.template($('#home-template').html()));
      }
    });
  });

}).call(this);
