// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      el: '#iframe-view',
      render: function() {
        return this.$el.html(_.template($('#iframe-template').html(), {
          'webPage': this.model.get('webPage')
        }));
      },
      initialize: function() {
        return this.model.bind('change:webPage', this.render, this);
      }
    });
  });

}).call(this);
