// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      el: '#navbar-view',
      render: function() {
        return this.$el.html(_.template($('#navbar-template').html()));
      },
      events: {
        'click button#set-web-page': 'setWebPage'
      },
      setWebPage: function() {
        return this.model.set('webPage', $('#web-page').val());
      }
    });
  });

}).call(this);
