// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone'], function(Backbone) {
    return Backbone.Model.extend({
      defaults: {
        'resultId': void 0,
        'description': void 0,
        'question': void 0,
        'answers': void 0,
        'template': '#test-case-template',
        'answer': void 0
      }
    });
  });

}).call(this);
