// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone'], function(Backbone) {
    return Backbone.Model.extend({
      defaults: {
        'webPage': 'http://ec.europa.eu/index_en.htm',
        'currentTest': 0
      },
      initialize: function(tests) {
        return this.set('tests', tests);
      },
      progress: function() {
        return parseInt((this.get('currentTest') / (this.get('tests').length - 1)) * 100);
      },
      isAtLast: function() {
        return this.get('currentTest') === (this.get('tests').length - 1);
      }
    });
  });

}).call(this);
