// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'socketio', 'collections/tests'], function(Backbone, io, Tests) {
    return Backbone.Model.extend({
      defaults: {
        'webPage': 'http://www.tingtun.no/',
        'currentTest': 0,
        'running': false
      },
      initialize: function(socket) {
        var that;
        this.set('socket', socket);
        this.set('tests', []);
        socket.emit('get tests', this.get('webPage'));
        that = this;
        socket.on('tests', function(data) {
          that.set('tests', new Tests(_.first(data, 10)));
          return that.set('running', true);
        });
        return this.bind('change:webPage', this.fetchTests, this);
      },
      fetchTests: function() {
        this.set('running', false);
        return this.get('socket').emit('get tests', this.get('webPage'));
      },
      progress: function() {
        return parseInt((this.get('currentTest') / (this.get('tests').length - 1)) * 100);
      },
      isAtLast: function() {
        return this.get('currentTest') === (this.get('tests').length - 1);
      },
      isAtFirst: function() {
        return this.get('currentTest') === 0;
      }
    });
  });

}).call(this);
