// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone'], function(Backbone) {
    return Backbone.Model.extend({
      defaults: {
        'title': void 0,
        'question': void 0,
        'answers': ['Yes', 'No', 'Unsure'],
        'template': '#test-case-template',
        'result': {
          'answer': void 0,
          'comment': ''
        }
      }
    });
  });

}).call(this);
