// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone', 'models/test'], function(Backbone, Test) {
    return Backbone.Collection.extend({
      model: Test
    });
  });

}).call(this);
