// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'models/test'], function(Backbone, Test) {
    return Backbone.Collection.extend({
      model: Test
    });
  });

}).call(this);
